/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
create database if not exists `school_db`;
use `school_db`;
DROP TABLE IF EXISTS `Student`;

CREATE TABLE `Student` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `age` INT NOT NULL,
  `created_at` DATETIME NULL)
 ENGINE=InnoDB;

